### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by SamyakGangwal** [AkashM398/LetMeSleep#1]
stack trace:
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    attendZoom()
  File "main.py", line 14, in attendZoom
    x,y = pyautogui.locateCenterOnScreen('join.png', confidence = 0.8)
TypeError: cannot unpack non-iterable NoneType object

**Comment by AkashM398** [comment]
Hello @SamyakGangwal, yes I am aware of that issue, that is because the pyautogui not able to find the specific image from Zoom, so it returns None. 
To fix this I would suggest you to open Zoom App, take screen shot of Join Button, and crop it to the size of the image that I have already given. Then try again it will work..
Not sure why issue is being caused, maybe because of the pixel values or something else. So try to follow the above steps.

**Comment by SamyakGangwal** [comment]
it works now

**Comment by SamyakGangwal** [comment]
![join](https://user-images.githubusercontent.com/30174059/93178939-9ce73b00-f752-11ea-916b-d0e74a969863.png)
try with this image, maybe this might work

**Comment by AkashM398** [comment]
Good, let me close this issue then.
